In [12]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import math
from scipy import stats as st

In [13]:
df=pd.read_csv ("epl-goalScorer(20-21).csv")
df.head()

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,0,647,Harry Kane,35,3097,23,22.174859,14,7.577094,138,49,1,0,F,Tottenham,19,19.130183,24.995648,4.451257
1,1,1250,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,55,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236
2,2,1228,Bruno Fernandes,37,3117,18,16.019454,12,11.474996,121,95,6,0,M S,Manchester United,9,8.407840,26.911412,11.932285
3,3,453,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,75,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751
4,4,822,Patrick Bamford,38,3085,17,18.401863,7,3.782247,107,30,3,0,F S,Leeds,15,16.879525,23.394953,4.131796

In [14]:
#10 Player terbanyak mencetak gol
df_sorted = df.sort_values('goals', ascending=False)
df_top10goal = df_sorted.head(10)
print(df_top10goal[['player_name', 'goals']])

             player_name  goals
0             Harry Kane     23
1          Mohamed Salah     22
2        Bruno Fernandes     18
3          Son Heung-Min     17
4        Patrick Bamford     17
5  Dominic Calvert-Lewin     16
6            Jamie Vardy     15
7          Ollie Watkins     14
8         Ilkay Gündogan     13
9    Alexandre Lacazette     13

In [15]:
#10 player terlama durasi bermain
df_sorted = df.sort_values('time', ascending=False)
df_top10t= df_sorted.head(10)
print(df_top10t[['player_name', 'time']])

               player_name  time
296            Hugo Lloris  3420
378      Emiliano Martinez  3420
311      Kasper Schmeichel  3420
110  Pierre-Emile Højbjerg  3420
40           Stuart Dallas  3412
327           Matt Targett  3407
480            Luke Ayling  3400
204       Andrew Robertson  3391
55         Youri Tielemans  3359
7            Ollie Watkins  3330

In [16]:
#10 player terbanyak assist
df_sorted = df.sort_values('assists', ascending=False)
df_top10assist = df_sorted.head(10)
print(df_top10assist[['player_name', 'assists']])

         player_name  assists
0         Harry Kane       14
2    Bruno Fernandes       12
58   Kevin De Bruyne       11
3      Son Heung-Min       10
51     Jack Grealish       10
15   Marcus Rashford        9
6        Jamie Vardy        9
57          Raphinha        9
49       Timo Werner        8
281  Aaron Cresswell        8

In [19]:
#4 player pencetak gol terbanyak dari kesebelasan manchester city
df_Manchester = df[df['team_title'] == 'Manchester City']
df_Manchester_sorted = df_Manchester.sort_values('goals', ascending=False)
df_top4_Manchester = df_Manchester_sorted.nlargest(4, 'goals')
#print(df_top4_Manchester City)
df_top4_Manchester = df_top4_Manchester.nlargest(4, 'goals')
print(df_top4_Manchester[['player_name','team_title', 'goals']])

        player_name       team_title  goals
8    Ilkay Gündogan  Manchester City     13
22  Raheem Sterling  Manchester City     10
28     Riyad Mahrez  Manchester City      9
35    Gabriel Jesus  Manchester City      8

In [20]:
#kesebelasan mana pencetak gol terbanyak
df_goals_per_team = df.groupby('team_title')['goals'].sum()
df_goals_per_team_sorted = df_goals_per_team.sort_values(ascending=False)
tim_dengan_goal_terbanyak = df_goals_per_team_sorted.index[0]
print(tim_dengan_goal_terbanyak)

Manchester City

In [22]:
#Jumlah kartu kuning dan merah yang diterima pembuat assist  terbanyak?
df_assists = df.groupby('player_name')['assists'].sum()
df_assists_sorted = df_assists.sort_values(ascending=False)
top_assister = df_assists_sorted.index[0]
df_top_assist = df[df['player_name'] == top_assister]
total_cards = df_top_assist['red_cards'].sum() + df_top_assist['yellow_cards'].sum()
print(total_cards)

1

In [23]:
#Siapa yang jumlah assist dan golnya paling banyak dan dari kesebelasan mana?
df['total_assists'] = df.groupby('player_name')['assists'].transform('sum')
df['total_goals'] = df.groupby('player_name')['goals'].transform('sum')
df_sorted = df.sort_values(by=['total_assists', 'total_goals'], ascending=False)
df_result = df_sorted[['player_name', 'total_assists', 'total_goals', 'team_title']].head(5)
print(df_result.to_string())

        player_name  total_assists  total_goals         team_title
0        Harry Kane             14           23          Tottenham
2   Bruno Fernandes             12           18  Manchester United
58  Kevin De Bruyne             11            5    Manchester City
3     Son Heung-Min             10           17          Tottenham
51    Jack Grealish             10            6        Aston Villa

In [24]:
#5 kesebelasan yang menyumbangkan gol terbanyak
df_team_goals = df.groupby('team_title')['goals'].sum()
df_team_goals_sorted = df_team_goals.sort_values(ascending=False)
df_result = df_team_goals_sorted.head(5)
print(df_result.to_string())


#Urutkan pemain berdasarkan jumlah gol terbanyak tanpa mendapatkan kartu sama sekali!
df['total_cards'] = df['red_cards'] + df['yellow_cards']
df_min_cards = df.loc[df['total_cards'] == df['total_cards'].min()]
df_min_cards_sorted = df_min_cards.sort_values(by='goals', ascending=False)
df_result = df_min_cards_sorted[['player_name', 'total_cards', 'total_goals', 'team_title']]
print(df_result.to_string())

team_title
Manchester City      77
Manchester United    68
Tottenham            66
Liverpool            64
Leicester            64
                 player_name  total_cards  total_goals               team_title
1              Mohamed Salah            0           22                Liverpool
3              Son Heung-Min            0           17                Tottenham
13                Chris Wood            0           12                  Burnley
28              Riyad Mahrez            0            9          Manchester City
29             Harvey Barnes            0            9                Leicester
33              Jarrod Bowen            0            8                 West Ham
37                Phil Foden            0            8          Manchester City
50             Danny Welbeck            0            6                 Brighton
52             Tammy Abraham            0            6                  Chelsea
60           Callum Robinson            0            5     West Bromwich Albion
72              Raúl Jiménez            0            4  Wolverhampton Wanderers
97              Hélder Costa            0            3                    Leeds
104         Sébastien Haller            0            3                 West Ham
101                Josh Maja            0            3                   Fulham
81       Allan Saint-Maximin            0            3         Newcastle United
92               Matej Vydra            0            3                  Burnley
86              Ross Barkley            0            3      Aston Villa,Chelsea
84              Theo Walcott            0            3      Everton,Southampton
146            Eddie Nketiah            0            2                  Arsenal
154           Aaron Connolly            0            2                 Brighton
152       Gabriel Martinelli            0            2                  Arsenal
150                Trézéguet            0            2              Aston Villa
149         Emile Smith-Rowe            0            2                  Arsenal
124          Michy Batshuayi            0            2           Crystal Palace
145       Callum Hudson-Odoi            0            2                  Chelsea
142              Solly March            0            2                 Brighton
136             Serge Aurier            0            2                Tottenham
111            Sergio Agüero            0            2          Manchester City
209          Martin Odegaard            0            1                  Arsenal
266          Daniel Jebbison            0            1         Sheffield United
265           Fabio Carvalho            0            1                   Fulham
256              Jimmy Dunne            0            1                  Burnley
245          Conor Hourihane            0            1              Aston Villa
233       Morgan Gibbs-White            0            1  Wolverhampton Wanderers
227          Rayan Ait Nouri            0            1  Wolverhampton Wanderers
225           Grady Diangana            0            1     West Bromwich Albion
222          Victor Lindelöf            0            1        Manchester United
220     Jean-Philippe Mateta            0            1           Crystal Palace
211            Said Benrahma            0            1                 West Ham
208             Willian José            0            1  Wolverhampton Wanderers
197             Dennis Praet            0            1                Leicester
196             Keinan Davis            0            1              Aston Villa
192  Alex Oxlade-Chamberlain            0            1                Liverpool
185          Andros Townsend            0            1           Crystal Palace
181             Dwight Gayle            0            1         Newcastle United
180                  Willian            0            1                  Arsenal
172         Jordan Henderson            0            1                Liverpool
166               Alex Iwobi            0            1                  Everton
163             Adam Lallana            0            1                 Brighton
206          Antonio Rüdiger            0            1                  Chelsea
487    Konstantinos Tsimikas            0            0                Liverpool
475              Jake Vokins            0            0              Southampton
467        William Smallbone            0            0              Southampton
468               Oskar Buur            0            0  Wolverhampton Wanderers
472            João Virgínia            0            0                  Everton
474   Bailey Peacock-Farrell            0            0                  Burnley
482        Ian Poveda-Ocampo            0            0                    Leeds
478              Marek Rodák            0            0                   Fulham
479            Illan Meslier            0            0                    Leeds
481         Jamie Shackleton            0            0                    Leeds
462           Anthony Gordon            0            0                  Everton
485             Kyle Edwards            0            0     West Bromwich Albion
463             Scott Carson            0            0          Manchester City
455            Billy Gilmour            0            0                  Chelsea
461       Amad Diallo Traore            0            0        Manchester United
459         Brandon Williams            0            0        Manchester United
458              Eric Garcia            0            0          Manchester City
456        Matthew Longstaff            0            0         Newcastle United
454    Daniel N&#039;Lundulu            0            0              Southampton
453        Caoimhin Kelleher            0            0                Liverpool
452             Zack Steffen            0            0          Manchester City
451                   Wesley            0            0              Aston Villa
445      Jack O&#039;Connell            0            0         Sheffield United
438              Will Norris            0            0                  Burnley
437              Josh Benson            0            0                  Burnley
432               Yan Valery            0            0              Southampton
486                  Vitinha            0            0  Wolverhampton Wanderers
517   Jaden Philogene-Bidace            0            0              Aston Villa
489               Liam Delap            0            0          Manchester City
490           Conor Townsend            0            0     West Bromwich Albion
520              Femi Seriki            0            0         Sheffield United
519           Anthony Elanga            0            0        Manchester United
518          Gaetano Berardi            0            0                    Leeds
425          Mohammed Salisu            0            0              Southampton
516         Nathan Broadhead            0            0                  Everton
515           Sidnei Tavares            0            0                Leicester
514          Shola Shoretire            0            0        Manchester United
513       Carney Chukwuemeka            0            0              Aston Villa
512            Dane Scarlett            0            0                Tottenham
511       Thakgalo Leshabela            0            0                Leicester
510            Iliman Ndiaye            0            0         Sheffield United
509              Jakub Moder            0            0                 Brighton
508         Allan Tchaptchet            0            0              Southampton
506              Reda Khadra            0            0                 Brighton
505                Percy Tau            0            0                 Brighton
504        Antwoine Hackford            0            0         Sheffield United
503            Niall Huggins            0            0                    Leeds
502            Theo Corbeanu            0            0  Wolverhampton Wanderers
501          Elliot Anderson            0            0         Newcastle United
500              Andi Zeqiri            0            0                 Brighton
498            Rhys Williams            0            0                Liverpool
497         Lewis Richardson            0            0                  Burnley
496         Filip Krovinovic            0            0     West Bromwich Albion
494             Jacob Ramsey            0            0              Aston Villa
492               Leif Davis            0            0                    Leeds
430                 Tim Ream            0            0                   Fulham
348         Shkodran Mustafi            0            0                  Arsenal
423     Rúnar Alex Rúnarsson            0            0                  Arsenal
336                Sam Field            0            0     West Bromwich Albion
324             Jack Butland            0            0           Crystal Palace
323           Charlie Austin            0            0     West Bromwich Albion
321               Shane Long            0            0              Southampton
319           Fraser Forster            0            0              Southampton
318               John Ruddy            0            0  Wolverhampton Wanderers
315             Demarai Gray            0            0                Leicester
312               Wes Morgan            0            0                Leicester
311        Kasper Schmeichel            0            0                Leicester
308           DeAndre Yedlin            0            0         Newcastle United
303            Fikayo Tomori            0            0                  Chelsea
298                Dele Alli            0            0                Tottenham
296              Hugo Lloris            0            0                Tottenham
293          Willy Caballero            0            0                  Chelsea
288           Seamus Coleman            0            0                  Everton
287             Odion Ighalo            0            0        Manchester United
286                Juan Mata            0            0        Manchester United
284             David de Gea            0            0        Manchester United
282          Darren Randolph            0            0                 West Ham
278                   Adrián            0            0                Liverpool
277             Martin Kelly            0            0           Crystal Palace
275           Calum Chambers            0            0                  Arsenal
273            Mamadou Sakho            0            0           Crystal Palace
272             Divock Origi            0            0                Liverpool
271              Joshua King            0            0                  Everton
269           Sead Kolasinac            0            0                  Arsenal
335             Joseph Gomez            0            0                Liverpool
338             Jonjoe Kenny            0            0                  Everton
422            Rúben Vinagre            0            0  Wolverhampton Wanderers
339          Felipe Anderson            0            0                 West Ham
419             David Button            0            0     West Bromwich Albion
417          Neeskens Kebano            0            0                   Fulham
414          Martin Dubravka            0            0         Newcastle United
413          Michael Obafemi            0            0              Southampton
412             Reiss Nelson            0            0                  Arsenal
408                Joe Rodon            0            0                Tottenham
406           Jayson Molumby            0            0                 Brighton
402           José Izquierdo            0            0                 Brighton
400             Cengiz Ünder            0            0                Leicester
398          Terence Kongolo            0            0                   Fulham
394             Davy Pröpper            0            0                 Brighton
387            Rekeem Harper            0            0     West Bromwich Albion
383                 Bernardo            0            0                 Brighton
381          Patrick Cutrone            0            0  Wolverhampton Wanderers
379     Jean-Philippe Gbamin            0            0                  Everton
377             Ahmed Hegazy            0            0     West Bromwich Albion
372           Kamil Grosicki            0            0     West Bromwich Albion
371      Oleksandr Zinchenko            0            0          Manchester City
364                    Jonny            0            0  Wolverhampton Wanderers
363             Kiko Casilla            0            0                    Leeds
359              Alex Telles            0            0        Manchester United
353              Lys Mousset            0            0         Sheffield United
343            Islam Slimani            0            0                Leicester
341               Moise Kean            0            0                  Everton
340                  Emerson            0            0                  Chelsea
521          Tyrese Francois            0            0                   Fulham